
#Registrar usuario
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "validation100@mail.com",
  "password": "12345678"
}


###

#Validar email
PUT http://localhost:3000/api/user/validation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWQ1NzQzYWYxZTRhZjIzYjEwN2NlY2IiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzU1OTY2MDIsImV4cCI6MTc3NTU5NzUwMn0.ehlm8aGUsAbLs1H0yvpn_xkWrm5-lmujklDfs0whpIo

{
  "code": "504006"
}

###

#Hacer login
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "validation0@mail.com",
  "password": "12345678"
}

###

#Refrescar Token
POST http://localhost:3000/api/user/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWQ0YjYxOGYzYTZlYjVmNjBjOWY2Y2EiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzU1OTE3NjMsImV4cCI6MTc3NjE5NjU2M30.VCUvx_4ndZTEwgM1y_DkZiUdEkYodS9f0I1j_q3Wdtc"
}


###

#Logout
POST http://localhost:3000/api/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWQ0YjU5NmYzYTZlYjVmNjBjOWY2YmEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzU1NTUyNjQsImV4cCI6MTc3NTU1NjE2NH0.9Eq1PXgT-B-wIq1ZIEZzDqfZ0qyKpU6M7QKu789OYHs

###

#Onboarding data user
PUT http://localhost:3000/api/user/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWQ0YzgxOGRmOTEwY2VhMGRkMjcxZDQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzU1NTg5NTMsImV4cCI6MTc3NTU1OTg1M30.BolqmPMowZbX6CBIrAG6Aa9nnqxHk-9lvi9897QDRdE

{
  "name": "Marco",
  "lastName": "Pérez Roldán",
  "nif": "30839276N",
  "address": {
    "street": "Cañada",
    "number": "55",
    "postal": "22620",
    "city": "Madrid",
    "province": "Madrid"
  }
}

###

#Onboarding company autónomo
PATCH http://localhost:3000/api/user/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWQ0YjYxOGYzYTZlYjVmNjBjOWY2Y2EiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzU1NTg3NDQsImV4cCI6MTc3NTU1OTY0NH0.IPyb1QryiylzzbAiMzJIBbDxbaIl7CjGOuHXPtqO6Fw

{
  "name": "Temporal",
  "cif": "TEMP12345",
  "address": {
    "street": "Calle Real",
    "number": "1",
    "postal": "41001",
    "city": "Sevilla",
    "province": "Sevilla"
  },
  "isFreelance": true
}

###

#Onboarding company existente
PATCH http://localhost:3000/api/user/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWQ0YzgxOGRmOTEwY2VhMGRkMjcxZDQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzU1NTg5NTMsImV4cCI6MTc3NTU1OTg1M30.BolqmPMowZbX6CBIrAG6Aa9nnqxHk-9lvi9897QDRdE

{
  "name": "Empresa Nueva SL",
  "cif": "B12345678",
  "address": {
    "street": "Mayor",
    "number": "10",
    "postal": "28001",
    "city": "Madrid",
    "province": "Madrid"
  },
  "isFreelance": false
}
###

#Onboarding company nueva

PATCH http://localhost:3000/api/user/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWQ0ZGQ3ZmIxMzFlYmM1YTBlZGI4ODgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzU1NTgwMTUsImV4cCI6MTc3NTU1ODkxNX0.S9A9bd8piWkoXAIPQpVG6D0hHK2fPTM39dzXRjSMsss

{
  "name": "Empresa Nueva SL",
  "cif": "B12345678",
  "address": {
    "street": "Mayor",
    "number": "10",
    "postal": "28001",
    "city": "Madrid",
    "province": "Madrid"
  },
  "isFreelance": false
}

###

#Upload logo company
PATCH http://localhost:3000/api/user/logo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWQ0YzgxOGRmOTEwY2VhMGRkMjcxZDQiLCJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3NzU1NjA3NzQsImV4cCI6MTc3NTU2MTY3NH0.TG581cUQgqBAI4lEK_6dKaahyU2Gwmx14_xgg03tfw8
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="logo"; filename="descarga.png"
Content-Type: image/png

< ./test/logo.png
--boundary--


###

#Get user
GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWQ0YjYxOGYzYTZlYjVmNjBjOWY2Y2EiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzU1OTY5MzMsImV4cCI6MTc3NTU5NzgzM30.Qk58DECMzenPOURj2sIePxTwRjhxEWdURshEAqpY-uw

###

#Invitar compañeros
POST http://localhost:3000/api/user/invite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWQ0YjYxOGYzYTZlYjVmNjBjOWY2Y2EiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzU1OTE3NjMsImV4cCI6MTc3NTU5MjY2M30.lJ9hkdOBbJ9ijHCV0ues4rTw1J3AoxipWvqZGKnjHGk

{
  "email": "invitado4@mail.com"
}

###

#Borrar usuario
DELETE http://localhost:3000/api/user?soft=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWQ1NzQzYWYxZTRhZjIzYjEwN2NlY2IiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzU1OTY2MDIsImV4cCI6MTc3NTU5NzUwMn0.ehlm8aGUsAbLs1H0yvpn_xkWrm5-lmujklDfs0whpIo

###

#Cambiar contraseña
PUT http://localhost:3000/api/user/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWQ0ZmI2MmZhYzE5ZmFkZTJhNmJmMGMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzU1NjU2NjYsImV4cCI6MTc3NTU2NjU2Nn0.Mz0EEnMX8mOeLAlGGUddPJumpimRvmXIleARObLeluM


{
  "currentPassword": "87654321",
  "newPassword": "87654321"
}


###

GET http://localhost:3000/api/image/pdf